[package]
name = "memflow-native"
version = "0.1.0"
authors = ["Aurimas Blažulionis <0x60@pm.me>"]
edition = "2018"
description = "System call based proxy-OS for memflow"
readme = "README.md"
license = "LICENSE"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
#cglue = { path = "../cglue/cglue/" }
#memflow = { path = "../memflow/memflow", features = ["plugins"] }
memflow = { git = "https://github.com/memflow/memflow", branch = "next", features = ["plugins"] }
memflow-derive = { git = "https://github.com/memflow/memflow.git", branch = "next" }
log = "0.4"
libc = { version = "0.2.90" }
itertools = "0.10"
goblin = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.9", features = ["backtrace"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.29", features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Diagnostics_Debug",
	"Win32_System_Threading",
	"Win32_System_ProcessStatus",
] }
