[package]
name = "memflow-native"
version = "0.2.0-beta9"
authors = ["Aurimas Blažulionis <0x60@pm.me>", "ko1N <ko1N1337@gmail.com>"]
edition = "2018"
description = "System call based proxy-OS for memflow"
readme = "README.md"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
memflow = { version = "^0.2.0-beta9", features = ["plugins"] }
#memflow = { path = "../memflow/memflow", features = ["plugins"] }
log = "0.4"
libc = { version = "0.2.90" }
itertools = "0.10"
goblin = "^0.6"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "^0.13.3", features = ["backtrace"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "^0.38", features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Diagnostics_Debug",
	"Win32_System_Threading",
	"Win32_System_ProcessStatus",
	"Win32_Security",
	"Win32_System_Memory"
] }

[features]
default = []
plugins = []
